package com.example.unscramble.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFFF9800) // Naranja
val md_theme_light_onPrimary = Color(0xFFFFFFFF) // Blanco sobre naranja
val md_theme_light_primaryContainer = Color(0xFFFFE0B2) // Naranja claro
val md_theme_light_onPrimaryContainer = Color(0xFF3E2723) // Naranja oscuro
val md_theme_light_secondary = Color(0xFFFFA726) // Naranja más claro
val md_theme_light_onSecondary = Color(0xFF000000) // Negro
val md_theme_light_secondaryContainer = Color(0xFFFFCC80) // Naranja muy claro
val md_theme_light_onSecondaryContainer = Color(0xFFBF360C) // Naranja oscuro
val md_theme_light_tertiary = Color(0xFFFF7043) // Tono naranja rojizo
val md_theme_light_onTertiary = Color(0xFFFFFFFF) // Blanco
val md_theme_light_tertiaryContainer = Color(0xFFFFAB91) // Naranja claro
val md_theme_light_onTertiaryContainer = Color(0xFF3E2723) // Marrón oscuro
val md_theme_light_error = Color(0xFFB71C1C) // Rojo
val md_theme_light_errorContainer = Color(0xFFFFCDD2) // Rojo claro
val md_theme_light_onError = Color(0xFFFFFFFF) // Blanco
val md_theme_light_onErrorContainer = Color(0xFF370617) // Rojo oscuro
val md_theme_light_background = Color(0xFFFFF3E0) // Fondo naranja claro
val md_theme_light_onBackground = Color(0xFF3E2723) // Marrón oscuro
val md_theme_light_surface = Color(0xFFFFF3E0) // Superficie naranja claro
val md_theme_light_onSurface = Color(0xFF3E2723) // Marrón oscuro
val md_theme_light_surfaceVariant = Color(0xFFFFCCBC) // Naranja pálido
val md_theme_light_onSurfaceVariant = Color(0xFF3E2723) // Marrón oscuro
val md_theme_light_outline = Color(0xFF8D6E63) // Marrón
val md_theme_light_inverseOnSurface = Color(0xFFFFF3E0) // Inverso fondo claro
val md_theme_light_inverseSurface = Color(0xFF3E2723) // Inverso fondo oscuro
val md_theme_light_inversePrimary = Color(0xFFFF6F00) // Naranja intenso
val md_theme_light_surfaceTint = Color(0xFFFF9800) // Naranja principal
val md_theme_light_outlineVariant = Color(0xFFD7CCC8) // Marrón claro
val md_theme_light_scrim = Color(0xFF000000) // Negro

val md_theme_dark_primary = Color(0xFFFF9800) // Naranja
val md_theme_dark_onPrimary = Color(0xFF3E2723) // Marrón oscuro
val md_theme_dark_primaryContainer = Color(0xFFFF6F00) // Naranja intenso
val md_theme_dark_onPrimaryContainer = Color(0xFFFFE0B2) // Naranja claro
val md_theme_dark_secondary = Color(0xFFFFA726) // Naranja claro
val md_theme_dark_onSecondary = Color(0xFF3E2723) // Marrón oscuro
val md_theme_dark_secondaryContainer = Color(0xFFFFB74D) // Naranja suave
val md_theme_dark_onSecondaryContainer = Color(0xFFFFE0B2) // Naranja claro
val md_theme_dark_tertiary = Color(0xFFFF7043) // Naranja rojizo
val md_theme_dark_onTertiary = Color(0xFF3E2723) // Marrón oscuro
val md_theme_dark_tertiaryContainer = Color(0xFFFF8A65) // Naranja rojizo suave
val md_theme_dark_onTertiaryContainer = Color(0xFFFFAB91) // Naranja claro
val md_theme_dark_error = Color(0xFFFF5252) // Rojo intenso
val md_theme_dark_errorContainer = Color(0xFFD32F2F) // Rojo oscuro
val md_theme_dark_onError = Color(0xFF3E2723) // Marrón oscuro
val md_theme_dark_onErrorContainer = Color(0xFFFFCDD2) // Rojo claro
val md_theme_dark_background = Color(0xFF3E2723) // Fondo oscuro marrón
val md_theme_dark_onBackground = Color(0xFFFFF3E0) // Blanco sobre fondo oscuro
val md_theme_dark_surface = Color(0xFF3E2723) // Superficie marrón oscuro
val md_theme_dark_onSurface = Color(0xFFFFF3E0) // Blanco sobre superficie marrón
val md_theme_dark_surfaceVariant = Color(0xFF795548) // Marrón
val md_theme_dark_onSurfaceVariant = Color(0xFFFFCCBC) // Naranja claro
val md_theme_dark_outline = Color(0xFFBCAAA4) // Marrón claro
val md_theme_dark_inverseOnSurface = Color(0xFF3E2723) // Marrón oscuro inverso
val md_theme_dark_inverseSurface = Color(0xFFFFF3E0) // Fondo claro inverso
val md_theme_dark_inversePrimary = Color(0xFFFF9800) // Naranja
val md_theme_dark_surfaceTint = Color(0xFFFF9800) // Naranja principal
val md_theme_dark_outlineVariant = Color(0xFF795548) // Marrón claro
val md_theme_dark_scrim = Color(0xFF000000) // Negro
